### ISSUE TITLE
Logging problem with simplemma

### ISSUE THREAD

**Issue by dokato** [adbar/simplemma#11]
Not sure necessarily if this problem should be addressed here, but I discovered it while using the package, so I thought I'd report.

In my app that uses simplemma, I have a logger configured like this:
```python
logging.basicConfig(level=logging.DEBUG,
                    handlers=[
                     logging.FileHandler("ocr.log"),
                     logging.StreamHandler(sys.stdout)
                    ])
```

But this causes errors, when it gets to line:
https://github.com/adbar/simplemma/blob/main/simplemma/simplemma.py#L389

```
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/opt/conda/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/user/./app/action.py", line 40, in <listcomp>
    text = " ".join([simplemma.lemmatize(x, lang=('it','en')) for x in text.split(' ') if len(x)])
  File "/opt/conda/lib/python3.8/site-packages/simplemma/simplemma.py", line 389, in lemmatize
    LOGGER.debug(token, candidate, 'found in %s', i)
```

Any other packages seem to work just fine with my logging definition.

**Comment by adbar** [comment]
Hi @dokato, thanks for pointing that out, it is a bug indeed. I was able to fix it in the commit above.

Please note that you might want to use the `text_lemmatizer()` function in your code instead of splitting the input on spaces.
