### ISSUE TITLE
unable to load simplemma.simplemma 

### ISSUE THREAD

**Issue by FrogInDizzy** [adbar/simplemma#136]
Hi @adbar  and I was trying to load LANGLIST 
```python
from simplemma import simple_tokenizer
from simplemma import text_lemmatizer as simple_lemmatizer
from simplemma.simplemma import LANGLIST

from .types import Gloss


def text_to_gloss(text: str, language: str) -> Gloss:
    if language not in LANGLIST:
        raise ValueError(f"Language {language} not supported")

    words = [w.lower() for w in simple_tokenizer(text)]
    lemmas = [w.lower() for w in simple_lemmatizer(text, lang=language)]

    return list(zip(words, lemmas))`
```

and this is the error

```
~/PycharmProjects/spoken-to-signed-translation main*                                                                                                   05:26:40 PM
spoken-to-signed-translation ❯ text_to_gloss --text "Kleine Kinder essen Pizza." --glosser simple --spoken-language de --signed-language sgg

Text to gloss
Input text: Kleine Kinder essen Pizza.
Traceback (most recent call last):
  File "/Users/wenyaogao/PycharmProjects/spoken-to-signed-translation/venv/bin/text_to_gloss", line 8, in <module>
    sys.exit(text_to_gloss())
  File "/Users/wenyaogao/PycharmProjects/spoken-to-signed-translation/venv/lib/python3.9/site-packages/spoken_to_signed/bin.py", line 76, in text_to_gloss
    gloss = _text_to_gloss(args.text, args.spoken_language, args.glosser)
  File "/Users/wenyaogao/PycharmProjects/spoken-to-signed-translation/venv/lib/python3.9/site-packages/spoken_to_signed/bin.py", line 13, in _text_to_gloss
    module = importlib.import_module(f"spoken_to_signed.text_to_gloss.{glosser}")
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/wenyaogao/PycharmProjects/spoken-to-signed-translation/venv/lib/python3.9/site-packages/spoken_to_signed/text_to_gloss/simple.py", line 3, in <module>
    from simplemma.simplemma import LANGLIST
ModuleNotFoundError: No module named 'simplemma.simplemma'
```
Thanks for helping!

**Comment by juanjoDiaz** [comment]
Hi @FrogInDizzy ,

Which version of simplemma are you using?
Since version 1.0.0, the way to get the list of supported languages is 

```python
from simplemma.strategies.dictionaries.dictionary_factory import SUPPORTED_LANGUAGES
```

**Comment by FrogInDizzy** [comment]
my version is 1.0.0 and it works after use your command, thanks!
